[package]
name = "cli_testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pbr = "1.0.4"
clap = { version = "3.0.14", features = ["derive"] }
rand = "0.8.4"
comfy-table = "5.0.0"
